Repository teeny-box/michi-backend, pull requests merged in 2024-06, with the labels that each got.

#33 docker, docker-compose 추가
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: For: Deploy, Type: Docs/Chore

#36 Chore: CI/CD 설정 파일 추가 및 배포 스크립트 작성 #34
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  ecosystem.config.js
  scripts/deploy.sh
  src/libs/common/firebase/firebase-admin.service.ts
Labels: For: Deploy, Type: Docs/Chore

#38 랜덤 채팅 기능 구현
  package.json
  src/domain/chat/chat.controller.ts
  src/domain/chat/dto/create-chatroom.dto.ts
  src/domain/chat/exceptions/chatroom.exception.ts
  src/domain/chat/socket/socket.gateway.ts
  src/domain/chat/socket/socket.module.ts
  src/domain/chat/socket/status.gateway.ts
  src/libs/common/exceptions/exception.enum.ts
  src/libs/common/redis-cache/redis-cache.service.ts
Labels: Type: Feature

#39 fcm 토큰 create user dto에 추가
  src/domain/auth/users/dto/create-user.dto.ts
Labels: Type: Feature

#40 Refactor e2e test cleanup
  package.json
  src/domain/chat/test/app.e2e-spec.ts
  src/domain/chat/test/jest-e2e.json
  src/domain/images/test/app.e2e-spec.ts
  src/domain/images/test/jest-e2e.json
  src/domain/posts/dto/create-post.dto.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/test/app.e2e-spec.ts
  src/domain/posts/test/jest-e2e.json
  test/app.e2e-spec.ts
  test/jest-e2e.json
Labels: Type: Refactor, Type: Test

#41 Fix: 알림 보낼 때 필드 추가
  src/domain/chat/socket/dto/send-notification.dto.ts
  src/libs/common/firebase/firebase-admin.service.ts
Labels: Type: Feature

#42 Feat: auth, users, posts controller 단위 테스트 추가
  package.json
  src/domain/auth/auth.controller.spec.ts
  src/domain/auth/users/users.controller.spec.ts
  src/domain/posts/posts.controller.spec.ts
Labels: Type: Test
