Repository teeny-box/michi-backend, pull requests merged in 2024-07, with the labels that each got.

#45 유저 디바이스 추가 및 알림 기능 추가
  src/app.module.ts
  src/common/client/client-info.interface.ts
  src/common/enums/app-type.enum.ts
  src/common/enums/notification-type.enum.ts
  src/common/enums/os-type.enum.ts
  src/common/exceptions/exception.enum.ts
  src/database/abstract.repository.ts
  src/domain/auth/users/schemas/user.schema.ts
  src/domain/auth/users/users.controller.ts
  src/domain/auth/users/users.service.ts
  src/domain/device/dto/client-info.dto.ts
  src/domain/device/dto/create-user-device.dto.ts
  src/domain/device/exceptions/user-device.exception.ts
  src/domain/device/schemas/user-device.schema.ts
  src/domain/device/user-device.controller.ts
  src/domain/device/user-device.module.ts
  src/domain/device/user-device.repository.ts
  src/domain/device/user-device.service.ts
  src/domain/firebase/exceptions/firebase.exception.ts
  src/domain/firebase/firebase-admin.service.ts
  src/domain/firebase/firebase.exception.ts
  src/domain/notification/@types/push-message-prirority.type.ts
  src/domain/notification/dto/send-notification.dto.ts
  src/domain/notification/global-notification.processor.ts
  src/domain/notification/notification.controller.ts
  src/domain/notification/notification.module.ts
  src/domain/notification/notification.processor.ts
  src/domain/notification/notification.repository.ts
  src/domain/notification/notification.service.ts
  src/domain/notification/schemas/notification.schema.ts
  src/domain/socket/data/socket.constants.ts
  src/domain/socket/socket.gateway.ts
  src/domain/socket/socket.module.ts
  test/auth.controller.spec.ts
  test/chat.controller.spec.ts
  test/chatroom.controller.spec.ts
  test/mocks/post.mock.ts
  test/mocks/user.mock.ts
  test/posts.controller.spec.ts
  test/socket.gateway.spec.ts
  test/users.controller.spec.ts
Labels: Type: Feature, Type: Refactor

#46 Feature roles guard
  src/common/decorators/role.decorator.ts
  src/common/interfaces/request-with-user.interface.ts
  src/common/interfaces/token-payload.interface.ts
  src/common/utils/password.utils.ts
  src/domain/auth/auth.controller.ts
  src/domain/auth/auth.service.ts
  src/domain/auth/guards/roles.guard.ts
  src/domain/auth/strategies/jwt.strategy.ts
  src/domain/auth/strategies/one-time.strategy.ts
  src/domain/auth/strategies/refresh.strategy.ts
  src/domain/auth/users/users.controller.ts
  src/domain/auth/users/users.service.ts
  src/domain/chat/chat.controller.ts
  src/domain/device/user-device.controller.ts
  src/domain/notification/notification.controller.ts
  src/domain/posts/posts.controller.ts
  test/posts.controller.spec.ts
  test/users.controller.spec.ts
Labels: Type: Feature, Type: Refactor, Type: Test

#48 Fix: 온라인 유저 응답 형식 유저 페이지네이션으로 변경
  src/database/abstract.repository.ts
  src/domain/auth/users/users.controller.ts
  src/domain/auth/users/users.service.ts
  test/users.controller.spec.ts
Labels: Type: Feature

#50 온라인 유저 조회 소켓 API로 변경
  docker-compose.yml
  src/common/dto/page/page-options.dto.ts
  src/domain/auth/users/users.controller.ts
  src/domain/socket/data/socket.constants.ts
  src/domain/socket/dto/socket-user-response.dto.ts
  src/domain/socket/socket.gateway.ts
  test/socket.gateway.spec.ts
  test/users.controller.spec.ts
Labels: Type: Docs/Chore, Type: Feature
