Repository teeny-box/michi-backend, pull requests merged in 2024-05, with the labels that each got.

#2 Feat: auth, user 구현
  apps/auth/src/@types/enums/user.enum.ts
  apps/auth/src/@types/http-response.ts
  apps/auth/src/auth.controller.ts
  apps/auth/src/auth.module.ts
  apps/auth/src/auth.service.ts
  apps/auth/src/common/utils/password.utils.ts
  apps/auth/src/exceptions/auth.exception.ts
  apps/auth/src/guards/jwt-auth.guard.ts
  apps/auth/src/guards/local-auth.guard.ts
  apps/auth/src/guards/refresh-auth.guard.ts
  apps/auth/src/interfaces/request-with-user.interface.ts
  apps/auth/src/interfaces/token-payload.interface.ts
  apps/auth/src/main.ts
  apps/auth/src/strategies/jwt.strategy.ts
  apps/auth/src/strategies/local.strategy.ts
  apps/auth/src/strategies/refresh.strategy.ts
  apps/auth/src/users/dto/create-user.dto.ts
  apps/auth/src/users/dto/update-user.dto.ts
  apps/auth/src/users/dto/user-response.dto.ts
  apps/auth/src/users/exceptions/users.exception.ts
  apps/auth/src/users/schemas/user.schema.ts
  apps/auth/src/users/users.controller.ts
  apps/auth/src/users/users.module.ts
  apps/auth/src/users/users.repository.ts
  apps/auth/src/users/users.service.ts
  apps/chat/src/chat.module.ts
  libs/common/src/database/abstract.repository.ts
  libs/common/src/exceptions/base.exception.interface.ts
  libs/common/src/exceptions/base.exception.ts
  libs/common/src/exceptions/exception.enum.ts
  libs/common/src/exceptions/exception.filter.ts
  libs/common/src/exceptions/uncatch.exception.ts
  libs/common/src/index.ts
  package-lock.json
  package.json
Labels: enhancement

#4 아이디 찾기, 비밀번호 변경 전 인증, 비밀번호 변경 api 추가
  apps/auth/src/auth.controller.ts
  apps/auth/src/auth.service.ts
  apps/auth/src/users/dto/auth-verification.dto.ts
  apps/auth/src/users/dto/change-password.dto.ts
  apps/auth/src/users/users.controller.ts
  apps/auth/src/users/users.service.ts
Labels: enhancement

#7 Feat: 아이디 중복체크 추가, 닉네임 중복체크 수정 #6
  apps/auth/src/auth.service.ts
  apps/auth/src/users/users.controller.ts
  apps/auth/src/users/users.service.ts
Labels: enhancement

#9 Feat: 아이디, 닉네임, 비밀번호 형식 유효성검사 추가 #8
  apps/auth/src/users/dto/create-user.dto.ts
Labels: enhancement

#11 Feat: 비밀번호 찾기 시 아이디 존재여부 체크 api 추가 #10
  apps/auth/src/users/users.controller.ts
  apps/auth/src/users/users.service.ts
Labels: enhancement

#13 Fix 12 token delivery
  apps/auth/src/auth.controller.ts
  apps/auth/src/auth.service.ts
  apps/auth/src/main.ts
  apps/auth/src/strategies/jwt.strategy.ts
  apps/auth/src/strategies/refresh.strategy.ts
  apps/auth/src/users/users.service.ts
  package-lock.json
  package.json
Labels: For: Models/DB, Type: Docs/Chore, Type: Refactor

#15 auth, user 커스텀 에러 구체화 후 적용, 내부 로직에서 기본 키 일관성 있게 사용하도록 수정
  apps/auth/src/auth.controller.ts
  apps/auth/src/auth.service.ts
  apps/auth/src/exceptions/auth.exception.ts
  apps/auth/src/exceptions/users.exception.ts
  apps/auth/src/interfaces/token-payload.interface.ts
  apps/auth/src/strategies/jwt.strategy.ts
  apps/auth/src/strategies/refresh.strategy.ts
  apps/auth/src/users/users.controller.ts
  apps/auth/src/users/users.service.ts
  libs/common/src/exceptions/exception.enum.ts
Labels: Type: Docs/Chore, Type: Feature, Type: Refactor

#19 Feature 17 redis
  apps/auth/src/auth.controller.ts
  apps/auth/src/auth.module.ts
  apps/auth/src/auth.service.ts
  apps/auth/src/guards/one-time-auth.guard.ts
  apps/auth/src/strategies/one-time.strategy.ts
  apps/auth/src/strategies/refresh.strategy.ts
  apps/auth/src/users/dto/change-password.dto.ts
  apps/auth/src/users/dto/check-for-password.dto.ts
  apps/auth/src/users/schemas/user.schema.ts
  apps/auth/src/users/users.controller.ts
  apps/auth/src/users/users.module.ts
  apps/auth/src/users/users.service.ts
  libs/common/src/config/redis-cache.config.ts
  libs/common/src/index.ts
  libs/common/src/redis-cache/redis-cache.module.ts
  libs/common/src/redis-cache/redis-cache.service.ts
  package-lock.json
  package.json
Labels: For: Models/DB, Type: Feature

#25 유저 온라인 상태 표시 및 채팅 응답 변경
  apps/auth/src/users/users.controller.ts
  apps/chat/src/dto/chat-response.dto.ts
  apps/chat/src/dto/chatroom-response.dto.ts
  apps/chat/src/socket/socket.gateway.ts
  apps/chat/src/socket/socket.module.ts
  apps/chat/src/socket/status.gateway.ts
  libs/common/src/@types/enums/common.enum.ts
  libs/common/src/redis-cache/redis-cache.service.ts
Labels: Type: Feature

#29 Feature 27 s3 integration
  apps/auth/src/users/dto/update-user.dto.ts
  apps/auth/src/users/users.service.ts
  apps/images/src/dto/delete-files.dto.ts
  apps/images/src/dto/presigned-url.dto.ts
  apps/images/src/images.controller.ts
  apps/images/src/images.module.ts
  apps/images/src/main.ts
  apps/images/test/app.e2e-spec.ts
  apps/images/test/jest-e2e.json
  apps/images/tsconfig.app.json
  libs/common/src/config/s3.config.ts
  libs/common/src/utils/s3.utils.ts
  nest-cli.json
  package-lock.json
  package.json
Labels: For: Utils, Type: Feature

#30 Feature 28 post
  apps/auth/src/common/utils/password.utils.ts
  apps/auth/src/exceptions/auth.exception.ts
  apps/auth/src/users/dto/user-response.dto.ts
  apps/auth/src/users/schemas/user.schema.ts
  apps/images/src/images.controller.ts
  apps/posts/src/dto/create-post.dto.ts
  apps/posts/src/dto/post-response.dto.ts
  apps/posts/src/dto/update-post.dto.ts
  apps/posts/src/exceptions/posts.exception.ts
  apps/posts/src/main.ts
  apps/posts/src/posts.controller.spec.ts
  apps/posts/src/posts.controller.ts
  apps/posts/src/posts.module.ts
  apps/posts/src/posts.repository.ts
  apps/posts/src/posts.service.ts
  apps/posts/src/schemas/post.schema.ts
  apps/posts/test/app.e2e-spec.ts
  apps/posts/test/jest-e2e.json
  apps/posts/tsconfig.app.json
  libs/common/src/counter/counter.module.ts
  libs/common/src/counter/counter.service.ts
  libs/common/src/counter/schemas/counter.schema.ts
  libs/common/src/database/abstract.repository.ts
  libs/common/src/exceptions/exception.enum.ts
  libs/common/src/index.ts
  nest-cli.json
  tsconfig.json
Labels: For: Models/DB, Type: Feature

#31 Feature 26 notification
  .gitignore
  apps/auth/src/users/dto/register-fcm-token.dto.ts
  apps/auth/src/users/schemas/user.schema.ts
  apps/auth/src/users/users.controller.ts
  apps/auth/src/users/users.service.ts
  apps/chat/src/dto/chat-response.dto.ts
  apps/chat/src/socket/socket.gateway.ts
  apps/chat/src/socket/socket.module.ts
  apps/chat/src/socket/status.gateway.ts
  apps/chat/test/chat.controller.spec.ts
  libs/common/src/@types/enums/common.enum.ts
  libs/common/src/exceptions/exception.enum.ts
  libs/common/src/firebase/firebase-admin.service.ts
  libs/common/src/firebase/firebase.exception.ts
  libs/common/src/notification/notification.module.ts
  libs/common/src/notification/notification.processor.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: For: API, Type: Feature
